global:
  buffer_size: '1000'
  sample_rate: 50
plots:
- channels:
  - cDAQ1Mod1/ai0
  - cDAQ1Mod1/ai1
  display_samples: '1000'
  title: null
  y_max: 0.8
  y_min: 0
  y_scale_mode: manual
- channels:
  - cDAQ1Mod1/ai2
  display_samples: '1000'
  title: null
  y_max: 0.5
  y_min: -0.5
  y_scale_mode: manual
- channels:
  - cDAQ1Mod1/ai3
  - cDAQ1Mod2/ai0
  display_samples: '1000'
  title: null
  y_max: 3
  y_min: -3
  y_scale_mode: manual
- channels: []
  display_samples: '1000'
  title: null
  y_max: 10
  y_min: -10
  y_scale_mode: auto
